In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df= pd.read_excel("default of credit card clients.xlsx")
df()

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,3,3,3,3,689,3,3,3,3,1
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,3272,3455,3261,3,1333,1333,1333,3,2333,1
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,14331,14948,15549,1518,1533,1333,1333,1333,5333,0
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,28314,28959,29547,2333,2319,1233,1133,1369,1333,0
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,23943,19146,19131,2333,36681,13333,9333,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,88334,31237,15983,8533,23333,5333,3347,5333,1333,0
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,8979,5193,3,1837,3526,8998,129,3,3,0
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,23878,23582,19357,3,3,22333,4233,2333,3133,1
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,52774,11855,48944,85933,3439,1178,1926,52964,1834,1
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,36535,32428,15313,2378,1833,1433,1333,1333,1333,1

In [ ]:
#add new column for credit utilization ratio
df["credit utilization ratio"]=df["BILL_AMT1"]/df["LIMIT_BAL"]
df

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month,credit utilization ratio
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,3,3,3,689,3,3,3,3,1,0.167702
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,3455,3261,3,1333,1333,1333,3,2333,1,0.021746
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,14948,15549,1518,1533,1333,1333,1333,5333,0,0.313276
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,28959,29547,2333,2319,1233,1133,1369,1333,0,0.881124
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,19146,19131,2333,36681,13333,9333,689,679,0,0.161570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,31237,15983,8533,23333,5333,3347,5333,1333,0,0.846037
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,5193,3,1837,3526,8998,129,3,3,0,0.010976
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,23582,19357,3,3,22333,4233,2333,3133,1,0.106951
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,11855,48944,85933,3439,1178,1926,52964,1834,1,-0.019740
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,32428,15313,2378,1833,1433,1333,1333,1333,1,0.898674

In [ ]:
#payment to bill ratio
df['pay_to_bill_ratio'] = df['PAY_AMT1'] / (df['BILL_AMT1'] + 1)
df

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month,credit utilization ratio,pay_to_bill_ratio
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,3,3,689,3,3,3,3,1,0.167702,0.000766
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,3261,3,1333,1333,1333,3,2333,1,0.021746,0.001118
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,15549,1518,1533,1333,1333,1333,5333,0,0.313276,0.051915
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,29547,2333,2319,1233,1133,1369,1333,0,0.881124,0.049645
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,19131,2333,36681,13333,9333,689,679,0,0.161570,0.270712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,15983,8533,23333,5333,3347,5333,1333,0,0.846037,0.045160
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,3,1837,3526,8998,129,3,3,0,0.010976,1.090855
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,19357,3,3,22333,4233,2333,3133,1,0.106951,0.000841
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,48944,85933,3439,1178,1926,52964,1834,1,-0.019740,-52.270681
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,15313,2378,1833,1433,1333,1333,1333,1,0.898674,0.049614

In [ ]:
#mean monthly bill
df['mean_monthly_bill'] = (df['BILL_AMT1'] + df['BILL_AMT2'] + df['BILL_AMT3'] + df['BILL_AMT4'] + df['BILL_AMT5'] + df['BILL_AMT6']) / 6
df

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month,credit utilization ratio,pay_to_bill_ratio,mean_monthly_bill
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,3,689,3,3,3,3,1,0.167702,0.000766,1290.500000
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,3,1333,1333,1333,3,2333,1,0.021746,0.001118,2846.166667
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,1518,1533,1333,1333,1333,5333,0,0.313276,0.051915,16992.166667
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,2333,2319,1233,1133,1369,1333,0,0.881124,0.049645,38556.166667
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,2333,36681,13333,9333,689,679,0,0.161570,0.270712,18724.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,8533,23333,5333,3347,5333,1333,0,0.846037,0.045160,125947.000000
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,1837,3526,8998,129,3,3,0,0.010976,1.090855,3536.333333
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,3,3,22333,4233,2333,3133,1,0.106951,0.000841,12749.333333
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,85933,3439,1178,1926,52964,1834,1,-0.019740,-52.270681,44440.166667
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,2378,1833,1433,1333,1333,1333,1,0.898674,0.049614,38484.000000

In [ ]:
#mean monthly payment
df['mean_monthly_payment'] = (df['PAY_AMT1'] + df['PAY_AMT2'] + df['PAY_AMT3'] + df['PAY_AMT4'] + df['PAY_AMT5'] + df['PAY_AMT6']) / 6
df

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month,credit utilization ratio,pay_to_bill_ratio,mean_monthly_bill,mean_monthly_payment
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,689,3,3,3,3,1,0.167702,0.000766,1290.500000,117.333333
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,1333,1333,1333,3,2333,1,0.021746,0.001118,2846.166667,1056.333333
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,1533,1333,1333,1333,5333,0,0.313276,0.051915,16992.166667,2063.833333
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,2319,1233,1133,1369,1333,0,0.881124,0.049645,38556.166667,1620.000000
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,36681,13333,9333,689,679,0,0.161570,0.270712,18724.166667,10508.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,23333,5333,3347,5333,1333,0,0.846037,0.045160,125947.000000,7868.666667
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,3526,8998,129,3,3,0,0.010976,1.090855,3536.333333,2416.000000
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,3,22333,4233,2333,3133,1,0.106951,0.000841,12749.333333,5339.666667
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,3439,1178,1926,52964,1834,1,-0.019740,-52.270681,44440.166667,24545.666667
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,1833,1433,1333,1333,1333,1,0.898674,0.049614,38484.000000,1607.166667

In [ ]:
#max payment delay
df['max_payment_delay'] = df[['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']].max(axis=1)
df

,ID,LIMIT_BAL,Gender,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,Default payment next month,credit utilization ratio,pay_to_bill_ratio,mean_monthly_bill,mean_monthly_payment,max_payment_delay
0,1,23333,2,Graduate University,2,24,2,2,-1,-1,...,3,3,3,3,1,0.167702,0.000766,1290.500000,117.333333,2
1,2,123333,2,Graduate University,1,26,-1,2,3,3,...,1333,1333,3,2333,1,0.021746,0.001118,2846.166667,1056.333333,3
2,3,93333,2,Graduate University,1,34,3,3,3,3,...,1333,1333,1333,5333,0,0.313276,0.051915,16992.166667,2063.833333,3
3,4,53333,2,Graduate University,2,37,3,3,3,3,...,1233,1133,1369,1333,0,0.881124,0.049645,38556.166667,1620.000000,3
4,5,53333,1,Graduate University,2,57,-1,3,-1,3,...,13333,9333,689,679,0,0.161570,0.270712,18724.166667,10508.000000,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,223333,1,Graduate High School,2,39,3,3,3,3,...,5333,3347,5333,1333,0,0.846037,0.045160,125947.000000,7868.666667,3
29996,29997,153333,1,Graduate High School,1,43,-1,-1,-1,-1,...,8998,129,3,3,0,0.010976,1.090855,3536.333333,2416.000000,3
29997,29998,33333,1,Graduate University,1,37,4,3,2,-1,...,22333,4233,2333,3133,1,0.106951,0.000841,12749.333333,5339.666667,4
29998,29999,83333,1,Graduate High School,2,41,1,-1,3,3,...,1178,1926,52964,1834,1,-0.019740,-52.270681,44440.166667,24545.666667,3
29999,33333,53333,1,Graduate University,2,46,3,3,3,3,...,1433,1333,1333,1333,1,0.898674,0.049614,38484.000000,1607.166667,3

In [ ]:

# # 2. Scale continuous numeric columns using StandardScaler
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# numeric_cols_to_scale = [
#     'LIMIT_BAL',
#     'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6',
#     'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
#     'mean_monthly_bill', 'mean_monthly_payment', 'credit utilization ratio', 'pay_to_bill_ratio',
#     'max_payment_delay'
# ]
# # Scale numeric columns directly in the dataframe
# df_encoded[numeric_cols_to_scale] = scaler.fit_transform(df_encoded[numeric_cols_to_scale])
# print("Task 3 Complete: Categoricals encoded and numeric features scaled.")

In [ ]:
# Save the updated DataFrame to a new Excel file
df.to_excel('default_of_credit_card_clients_processed.xlsx', index=False)

In [ ]:
from google.colab import files
files.download('default_of_credit_card_clients_processed.xlsx')